package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// The per-project specs wiki, generated and never hand-edited.
//
// The obvious build is a markdown parser; the extraction is line-shaped —
// prefixes, headings, bullets — so a scanner covers it and a parser would be a
// dependency bought to avoid twenty lines. What counts as a criterion is
// spec-drift's own definition, a bullet with a Proof: beneath it, because two
// tools with two definitions would disagree about what a capability promises.

// wikiMarker opens every generated file. It is how the tool recognises its own:
// a README whose first line is anything else was written by a person, and the
// oldest rule in this repository is that the tool never overwrites what it did
// not create.
const wikiMarker = "<!-- generated by libretto wiki; edit the specs, then run: libretto wiki -->"

// wikiDirOrder is spec-drift's discovery order, verbatim. First hit wins.
var wikiDirOrder = []string{".agents/specs", "specs", "openspec", "docs/specs", "spec"}

type wikiCapability struct {
	name     string
	governs  string
	intro    []string // prose before the first heading; absent is absent
	criteria []string // Proof:-backed bullets, without their Proof: lines
}

func wiki(w io.Writer, projectDir string) error {
	specsDir := ""
	for _, candidate := range wikiDirOrder {
		if info, err := os.Stat(filepath.Join(projectDir, candidate)); err == nil && info.IsDir() {
			specsDir = filepath.Join(projectDir, candidate)
			break
		}
	}
	if specsDir == "" {
		return fmt.Errorf("no specs directory found (looked for %s)", strings.Join(wikiDirOrder, ", "))
	}

	entries, err := os.ReadDir(specsDir) // sorted by name: determinism is structural
	if err != nil {
		return err
	}
	var caps []wikiCapability
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		specPath := filepath.Join(specsDir, e.Name(), "spec.md")
		f, err := os.Open(specPath)
		if err != nil {
			continue // a directory without a spec.md is not a capability
		}
		c := parseSpec(f, e.Name())
		f.Close()
		caps = append(caps, c)
	}
	if len(caps) == 0 {
		return fmt.Errorf("%s holds no */spec.md — an empty specification has nothing to index", specsDir)
	}

	readmePath := filepath.Join(specsDir, "README.md")
	if existing, err := os.ReadFile(readmePath); err == nil {
		first, _, _ := strings.Cut(string(existing), "\n")
		if first != wikiMarker {
			return fmt.Errorf("%s exists and was not generated by libretto wiki — not touching it", readmePath)
		}
	}
	if err := os.WriteFile(readmePath, renderWiki(projectDir, caps), 0o644); err != nil {
		return err
	}
	fmt.Fprintf(w, "wrote %s   (%d capabilities)\n", readmePath, len(caps))
	return nil
}

// parseSpec reads one capability spec in a single pass. The intro is the first
// run of prose lines before the first heading after the title; a criterion is a
// bullet block carrying a Proof: line, captured without it.
func parseSpec(r io.Reader, name string) wikiCapability {
	c := wikiCapability{name: name}
	var bullet []string
	bulletProven, introDone, inBullet := false, false, false

	flush := func() {
		if inBullet && bulletProven && len(bullet) > 0 {
			c.criteria = append(c.criteria, strings.Join(bullet, " "))
		}
		bullet, bulletProven, inBullet = nil, false, false
	}

	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)

		switch {
		case strings.HasPrefix(trimmed, "- "):
			flush()
			inBullet = true
			bullet = append(bullet, strings.TrimPrefix(trimmed, "- "))
			continue
		case inBullet && strings.HasPrefix(line, " ") && trimmed != "":
			if strings.HasPrefix(trimmed, "Proof:") {
				bulletProven = true
			} else {
				bullet = append(bullet, trimmed)
			}
			continue
		}
		flush()

		switch {
		case strings.HasPrefix(trimmed, "#"):
			introDone = introDone || strings.HasPrefix(trimmed, "##")
		case strings.HasPrefix(trimmed, "Governs:"):
			if c.governs == "" {
				c.governs = strings.TrimSpace(strings.TrimPrefix(trimmed, "Governs:"))
			}
		case strings.HasPrefix(trimmed, "Targets:"), trimmed == "":
			// structural, never prose
		default:
			if !introDone {
				c.intro = append(c.intro, trimmed)
			}
		}
	}
	flush()
	return c
}

func renderWiki(projectDir string, caps []wikiCapability) []byte {
	var b strings.Builder
	b.WriteString(wikiMarker + "\n\n")
	fmt.Fprintf(&b, "# Specs — %s\n\n", filepath.Base(projectDir))
	b.WriteString("| Capability | Governs | What it promises |\n|---|---|---|\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "| [%s](%s/spec.md) | `%s` | %s |\n",
			c.name, c.name, tableCell(c.governs), tableCell(firstSentence(c.intro)))
	}
	for _, c := range caps {
		fmt.Fprintf(&b, "\n## %s\n\n", c.name)
		if len(c.intro) > 0 {
			b.WriteString(strings.Join(c.intro, " ") + "\n\n")
		}
		if c.governs != "" {
			fmt.Fprintf(&b, "Governs: `%s`\n\n", c.governs)
		}
		for _, crit := range c.criteria {
			fmt.Fprintf(&b, "- %s\n", crit)
		}
		if len(c.criteria) > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "[full spec](%s/spec.md)\n", c.name)
	}
	return []byte(b.String())
}

func firstSentence(intro []string) string {
	if len(intro) == 0 {
		return ""
	}
	joined := strings.Join(intro, " ")
	if cut := strings.Index(joined, ". "); cut >= 0 {
		return joined[:cut+1]
	}
	return joined
}

// tableCell keeps a pipe in spec prose from tearing the index table apart.
func tableCell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }
