package main

import (
	"bufio"
	"fmt"
	"html"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// The per-project specs wiki, generated and never hand-edited.
//
// The obvious build is a markdown parser; the extraction is line-shaped —
// prefixes, headings, bullets — so a scanner covers it and a parser would be a
// dependency bought to avoid twenty lines. What counts as a criterion is
// spec-drift's own definition, a bullet with a Proof: beneath it, because two
// tools with two definitions would disagree about what a capability promises.

// wikiMarker opens every generated file. It is how the tool recognises its own:
// a README whose first line is anything else was written by a person, and the
// oldest rule in this repository is that the tool never overwrites what it did
// not create.
const wikiMarker = "<!-- generated by libretto wiki; edit the specs, then run: libretto wiki -->"

// wikiDirOrder is spec-drift's discovery order, verbatim. First hit wins.
var wikiDirOrder = []string{".agents/specs", "specs", "openspec", "docs/specs", "spec"}

type wikiCapability struct {
	name     string
	governs  string
	intro    []string // prose before the first heading; absent is absent
	criteria []string // Proof:-backed bullets, without their Proof: lines
}

// wikiHTMLMarker opens the generated viewer, first line, before the doctype —
// modern parsers allow a comment there and the ownership check stays one read.
const wikiHTMLMarker = "<!-- generated by libretto wiki; edit the specs, then run: libretto wiki --html -->"

func wiki(w io.Writer, projectDir string, args []string) error {
	htmlMode := false
	for _, a := range args {
		if a == "--html" {
			htmlMode = true
			continue
		}
		return fmt.Errorf("unknown argument %q — wiki takes only --html", a)
	}

	specsDir := ""
	for _, candidate := range wikiDirOrder {
		if info, err := os.Stat(filepath.Join(projectDir, candidate)); err == nil && info.IsDir() {
			specsDir = filepath.Join(projectDir, candidate)
			break
		}
	}
	if specsDir == "" {
		return fmt.Errorf("no specs directory found (looked for %s)", strings.Join(wikiDirOrder, ", "))
	}

	entries, err := os.ReadDir(specsDir) // sorted by name: determinism is structural
	if err != nil {
		return err
	}
	var caps []wikiCapability
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		specPath := filepath.Join(specsDir, e.Name(), "spec.md")
		f, err := os.Open(specPath)
		if err != nil {
			continue // a directory without a spec.md is not a capability
		}
		c := parseSpec(f, e.Name())
		f.Close()
		caps = append(caps, c)
	}
	if len(caps) == 0 {
		return fmt.Errorf("%s holds no */spec.md — an empty specification has nothing to index", specsDir)
	}

	if htmlMode {
		htmlPath := filepath.Join(specsDir, "wiki.html")
		if err := writeMarked(htmlPath, wikiHTMLMarker, renderWikiHTML(projectDir, caps)); err != nil {
			return err
		}
		fmt.Fprintf(w, "wrote %s   (%d capabilities)\n", htmlPath, len(caps))
		return nil
	}

	readmePath := filepath.Join(specsDir, "README.md")
	if err := writeMarked(readmePath, wikiMarker, renderWiki(projectDir, caps)); err != nil {
		return err
	}
	fmt.Fprintf(w, "wrote %s   (%d capabilities)\n", readmePath, len(caps))

	// A marked wiki.html refreshes in the same run, so the one landing-step
	// invocation keeps every view this tool owns current. A foreign one is left
	// alone silently — erroring here would block every landing regeneration.
	htmlPath := filepath.Join(specsDir, "wiki.html")
	if ownsFile(htmlPath, wikiHTMLMarker) {
		if err := os.WriteFile(htmlPath, renderWikiHTML(projectDir, caps), 0o644); err != nil {
			return err
		}
		fmt.Fprintf(w, "refreshed %s\n", htmlPath)
	}
	return nil
}

// ownsFile reports whether path exists and opens with marker.
func ownsFile(path, marker string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	first, _, _ := strings.Cut(string(b), "\n")
	return first == marker
}

// writeMarked is the one implementation of "never overwrite what the tool did
// not create" for every generated view: an existing file whose first line is not
// the marker is somebody's, and it stays theirs.
func writeMarked(path, marker string, content []byte) error {
	if b, err := os.ReadFile(path); err == nil {
		first, _, _ := strings.Cut(string(b), "\n")
		if first != marker {
			return fmt.Errorf("%s exists and was not generated by libretto wiki — not touching it", path)
		}
	}
	return os.WriteFile(path, content, 0o644)
}

// parseSpec reads one capability spec in a single pass. The intro is the first
// run of prose lines before the first heading after the title; a criterion is a
// bullet block carrying a Proof: line, captured without it.
func parseSpec(r io.Reader, name string) wikiCapability {
	c := wikiCapability{name: name}
	var bullet []string
	bulletProven, introDone, inBullet := false, false, false

	flush := func() {
		if inBullet && bulletProven && len(bullet) > 0 {
			c.criteria = append(c.criteria, strings.Join(bullet, " "))
		}
		bullet, bulletProven, inBullet = nil, false, false
	}

	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)

		switch {
		case strings.HasPrefix(trimmed, "- "):
			flush()
			inBullet = true
			bullet = append(bullet, strings.TrimPrefix(trimmed, "- "))
			continue
		case inBullet && strings.HasPrefix(line, " ") && trimmed != "":
			if strings.HasPrefix(trimmed, "Proof:") {
				bulletProven = true
			} else {
				bullet = append(bullet, trimmed)
			}
			continue
		}
		flush()

		switch {
		case strings.HasPrefix(trimmed, "#"):
			introDone = introDone || strings.HasPrefix(trimmed, "##")
		case strings.HasPrefix(trimmed, "Governs:"):
			if c.governs == "" {
				c.governs = strings.TrimSpace(strings.TrimPrefix(trimmed, "Governs:"))
			}
		case strings.HasPrefix(trimmed, "Targets:"), trimmed == "":
			// structural, never prose
		default:
			if !introDone {
				c.intro = append(c.intro, trimmed)
			}
		}
	}
	flush()
	return c
}

func renderWiki(projectDir string, caps []wikiCapability) []byte {
	var b strings.Builder
	b.WriteString(wikiMarker + "\n\n")
	fmt.Fprintf(&b, "# Specs — %s\n\n", filepath.Base(projectDir))
	b.WriteString("| Capability | Governs | What it promises |\n|---|---|---|\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "| [%s](%s/spec.md) | `%s` | %s |\n",
			c.name, c.name, tableCell(c.governs), tableCell(firstSentence(c.intro)))
	}
	for _, c := range caps {
		fmt.Fprintf(&b, "\n## %s\n\n", c.name)
		if len(c.intro) > 0 {
			b.WriteString(strings.Join(c.intro, " ") + "\n\n")
		}
		if c.governs != "" {
			fmt.Fprintf(&b, "Governs: `%s`\n\n", c.governs)
		}
		for _, crit := range c.criteria {
			fmt.Fprintf(&b, "- %s\n", crit)
		}
		if len(c.criteria) > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "[full spec](%s/spec.md)\n", c.name)
	}
	return []byte(b.String())
}

func firstSentence(intro []string) string {
	if len(intro) == 0 {
		return ""
	}
	joined := strings.Join(intro, " ")
	if cut := strings.Index(joined, ". "); cut >= 0 {
		return joined[:cut+1]
	}
	return joined
}

// tableCell keeps a pipe in spec prose from tearing the index table apart.
func tableCell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

// Inline markup arrives from spec prose. Escaping runs first, always: the
// conversions below operate on escaped text, so no raw spec byte ever reaches
// markup position. That order is the whole of the escaping criterion.
var (
	wikiBoldRe = regexp.MustCompile(`\*\*([^*]+)\*\*`)
	wikiCodeRe = regexp.MustCompile("`([^`]+)`")
)

func htmlInline(s string) string {
	s = html.EscapeString(s)
	s = wikiBoldRe.ReplaceAllString(s, "<strong>$1</strong>")
	s = wikiCodeRe.ReplaceAllString(s, "<code>$1</code>")
	return s
}

func renderWikiHTML(projectDir string, caps []wikiCapability) []byte {
	name := html.EscapeString(filepath.Base(projectDir))
	total := 0
	for _, c := range caps {
		total += len(c.criteria)
	}

	var b strings.Builder
	b.WriteString(wikiHTMLMarker + "\n")
	b.WriteString("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	fmt.Fprintf(&b, "<title>Specs — %s</title>\n", name)
	b.WriteString(`<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Public+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>` + wikiCSS + `</style>
</head>
<body>
<div class="layout">
<aside>
`)
	fmt.Fprintf(&b, "<p class=\"brand\">%s</p>\n<p class=\"sub\">Specification wiki</p>\n", name)
	b.WriteString("<input id=\"filter\" type=\"search\" placeholder=\"Filter criteria…\" aria-label=\"Filter criteria\">\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "<a class=\"nav-item\" href=\"#%s\"><span>%s</span><span class=\"count\">%d</span></a>\n",
			html.EscapeString(c.name), html.EscapeString(c.name), len(c.criteria))
	}
	b.WriteString("</aside>\n<main>\n<header class=\"top\">\n")
	fmt.Fprintf(&b, "<h1>Specs — %s</h1>\n", name)
	fmt.Fprintf(&b, "<p class=\"stats\">%d capabilities · %d criteria · generated by <code>libretto wiki --html</code></p>\n",
		len(caps), total)
	b.WriteString("</header>\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "<section class=\"cap\" id=\"%s\">\n<h2>%s</h2>\n",
			html.EscapeString(c.name), html.EscapeString(c.name))
		if len(c.intro) > 0 {
			fmt.Fprintf(&b, "<p class=\"intro\">%s</p>\n", htmlInline(strings.Join(c.intro, " ")))
		}
		if c.governs != "" {
			fmt.Fprintf(&b, "<p class=\"governs\"><span class=\"lbl\">Governs</span><code>%s</code></p>\n",
				html.EscapeString(c.governs))
		}
		if len(c.criteria) > 0 {
			b.WriteString("<ul class=\"crit\">\n")
			for _, crit := range c.criteria {
				fmt.Fprintf(&b, "<li>%s</li>\n", htmlInline(crit))
			}
			b.WriteString("</ul>\n")
		} else {
			b.WriteString("<p class=\"none\">No anchored criteria yet — this capability migrates when a delta lands on it.</p>\n")
		}
		b.WriteString("</section>\n")
	}
	b.WriteString("</main>\n</div>\n<script>" + wikiJS + "</script>\n</body>\n</html>\n")
	return []byte(b.String())
}

const wikiCSS = `
:root{--ground:#FAF8F4;--panel:#F1EEE7;--ink:#22231F;--ink-soft:#5C5D55;
--line:#DDD9CE;--accent:#1E6E60;--accent-soft:#E3EEEA;--code-bg:#ECE9E0}
@media (prefers-color-scheme: dark){:root{--ground:#17181A;--panel:#1E2023;
--ink:#E6E4DC;--ink-soft:#9B9C93;--line:#33352F;--accent:#5CB8A6;
--accent-soft:#20342F;--code-bg:#26282B}}
*{box-sizing:border-box}
body{margin:0;background:var(--ground);color:var(--ink);
font:400 16px/1.6 "Public Sans",system-ui,sans-serif}
.layout{display:grid;grid-template-columns:270px 1fr;min-height:100vh}
aside{background:var(--panel);border-right:1px solid var(--line);
padding:1.5rem 1rem;position:sticky;top:0;height:100vh;overflow-y:auto;
display:flex;flex-direction:column;gap:.35rem}
.brand{font-family:"Fraunces",Georgia,serif;font-weight:600;font-size:1.3rem;
margin:0 .5rem .1rem}
.sub{margin:0 .5rem 1rem;font-size:.78rem;color:var(--ink-soft);
text-transform:uppercase;letter-spacing:.08em}
#filter{margin:0 .25rem 1rem;padding:.5rem .7rem;border:1px solid var(--line);
border-radius:6px;background:var(--ground);color:var(--ink);font:inherit;font-size:.88rem}
#filter:focus{outline:2px solid var(--accent);outline-offset:1px}
.nav-item{display:flex;justify-content:space-between;align-items:baseline;gap:.75rem;
padding:.32rem .6rem;border-radius:6px;color:var(--ink);text-decoration:none;
font-size:.92rem;font-weight:500}
.nav-item:hover,.nav-item:focus-visible{background:var(--accent-soft);outline:none}
.nav-item .count{font:500 .75rem "IBM Plex Mono",monospace;color:var(--ink-soft)}
main{padding:2.5rem clamp(1.5rem,5vw,4rem);max-width:60rem}
header.top h1{font-family:"Fraunces",Georgia,serif;font-weight:600;
font-size:clamp(1.7rem,4vw,2.3rem);margin:0 0 .4rem}
.stats{color:var(--ink-soft);font-size:.9rem}
.cap{border-top:1px solid var(--line);margin-top:2.4rem;padding-top:1.6rem}
.cap h2{font-family:"Fraunces",Georgia,serif;font-weight:600;font-size:1.4rem;
margin:0 0 .6rem;scroll-margin-top:1rem}
.intro{max-width:44rem;margin:.3rem 0 .9rem}
.governs{display:flex;gap:.7rem;align-items:baseline;flex-wrap:wrap;margin:.4rem 0 1rem}
.governs .lbl{font-size:.72rem;text-transform:uppercase;letter-spacing:.09em;
color:var(--accent);font-weight:600}
code{font:400 .86em "IBM Plex Mono",monospace;background:var(--code-bg);
padding:.1em .35em;border-radius:4px}
.crit{margin:.4rem 0 0;padding-left:1.1rem;display:flex;flex-direction:column;gap:.55rem}
.crit li{max-width:46rem}
.crit li::marker{color:var(--accent)}
.none{color:var(--ink-soft);font-style:italic;font-size:.92rem;max-width:44rem}
.hidden{display:none}
@media (max-width:760px){.layout{grid-template-columns:1fr}
aside{position:static;height:auto;border-right:none;border-bottom:1px solid var(--line)}}
@media (prefers-reduced-motion:no-preference){html{scroll-behavior:smooth}}
`

const wikiJS = `
const input=document.getElementById('filter');
input.addEventListener('input',()=>{
  const q=input.value.trim().toLowerCase();
  document.querySelectorAll('.cap').forEach(sec=>{
    let any=false;
    sec.querySelectorAll('.crit li').forEach(li=>{
      const hit=!q||li.textContent.toLowerCase().includes(q);
      li.classList.toggle('hidden',!hit); if(hit&&q) any=true;
    });
    sec.classList.toggle('hidden',!!q&&!any&&!sec.id.toLowerCase().includes(q));
  });
});
`
