package main

import (
	"bufio"
	"fmt"
	"html"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
)

// The per-project specs wiki, generated and never hand-edited.
//
// The obvious build is a markdown parser; the extraction is line-shaped —
// prefixes, headings, bullets — so a scanner covers it and a parser would be a
// dependency bought to avoid twenty lines. What counts as a criterion is
// spec-drift's own definition, a bullet with a Proof: beneath it, because two
// tools with two definitions would disagree about what a capability promises.

// wikiMarker opens every generated file. It is how the tool recognises its own:
// a README whose first line is anything else was written by a person, and the
// oldest rule in this repository is that the tool never overwrites what it did
// not create.
const wikiMarker = "<!-- generated by libretto wiki; edit the specs, then run: libretto wiki -->"

// wikiDirOrder is spec-drift's discovery order, verbatim. First hit wins.
var wikiDirOrder = []string{".agents/specs", "specs", "openspec", "docs/specs", "spec"}

type wikiCapability struct {
	name     string
	changed  string // last-changed date from git; empty is absent, never an error
	governs  string
	intro    []string // prose before the first heading; absent is absent
	criteria []string // Proof:-backed bullets, without their Proof: lines
}

// wikiHTMLMarker opens the generated viewer, first line, before the doctype —
// modern parsers allow a comment there and the ownership check stays one read.
const wikiHTMLMarker = "<!-- generated by libretto wiki; edit the specs, then run: libretto wiki --html -->"

func wiki(w io.Writer, projectDir string, args []string) error {
	htmlMode, openMode := false, false
	for _, a := range args {
		switch a {
		case "--html":
			htmlMode = true
		case "--open":
			// Opening implies the view being opened — a browser does not render
			// the markdown side.
			htmlMode, openMode = true, true
		default:
			return fmt.Errorf("unknown argument %q — wiki takes only --html and --open", a)
		}
	}

	specsDir, found := findSpecsDir(projectDir)
	if !found {
		return fmt.Errorf("no specs directory found (looked for %s)", strings.Join(wikiDirOrder, ", "))
	}

	entries, err := os.ReadDir(specsDir) // sorted by name: determinism is structural
	if err != nil {
		return err
	}
	var caps []wikiCapability
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		specPath := filepath.Join(specsDir, e.Name(), "spec.md")
		f, err := os.Open(specPath)
		if err != nil {
			continue // a directory without a spec.md is not a capability
		}
		c := parseSpec(f, e.Name())
		f.Close()
		c.changed = wikiGitDate(projectDir, specPath)
		caps = append(caps, c)
	}
	if len(caps) == 0 {
		return fmt.Errorf("%s holds no */spec.md — an empty specification has nothing to index", specsDir)
	}

	if htmlMode {
		htmlPath := filepath.Join(specsDir, "wiki.html")
		if err := writeMarked(htmlPath, wikiHTMLMarker, renderWikiHTML(projectDir, caps)); err != nil {
			return err
		}
		fmt.Fprintf(w, "wrote %s   (%d capabilities)\n", htmlPath, len(caps))
		if openMode {
			// Only after a successful write. A failed open leaves the file — the
			// error names it so the user can open it by hand.
			if err := openViewer(htmlPath); err != nil {
				return fmt.Errorf("wrote %s but could not open it: %w", htmlPath, err)
			}
			fmt.Fprintf(w, "opened %s\n", htmlPath)
		}
		return nil
	}

	readmePath := filepath.Join(specsDir, "README.md")
	if err := writeMarked(readmePath, wikiMarker, renderWiki(projectDir, caps)); err != nil {
		return err
	}
	fmt.Fprintf(w, "wrote %s   (%d capabilities)\n", readmePath, len(caps))

	// A marked wiki.html refreshes in the same run, so the one landing-step
	// invocation keeps every view this tool owns current. A foreign one is left
	// alone silently — erroring here would block every landing regeneration.
	htmlPath := filepath.Join(specsDir, "wiki.html")
	if ownsFile(htmlPath, wikiHTMLMarker) {
		if err := os.WriteFile(htmlPath, renderWikiHTML(projectDir, caps), 0o644); err != nil {
			return err
		}
		fmt.Fprintf(w, "refreshed %s\n", htmlPath)
	}
	return nil
}

// openerArgv is pure so the platform mapping is testable without executing it.
func openerArgv(goos, path string) []string {
	if goos == "darwin" {
		return []string{"open", path}
	}
	return []string{"xdg-open", path}
}

// openViewer hands a file to the platform's opener, detached — Start, not Run,
// so a misconfigured handler cannot block the panel mid-action. A var so tests
// observe the call instead of launching browsers.
var openViewer = func(path string) error {
	argv := openerArgv(runtime.GOOS, path)
	return exec.Command(argv[0], argv[1:]...).Start()
}

// findSpecsDir is the one discovery both the command and the panel's row share —
// a second list would disagree with this one exactly when it matters.
func findSpecsDir(projectDir string) (string, bool) {
	for _, candidate := range wikiDirOrder {
		if info, err := os.Stat(filepath.Join(projectDir, candidate)); err == nil && info.IsDir() {
			return filepath.Join(projectDir, candidate), true
		}
	}
	return "", false
}

// ownsFile reports whether path exists and opens with marker.
func ownsFile(path, marker string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	first, _, _ := strings.Cut(string(b), "\n")
	return first == marker
}

// writeMarked is the one implementation of "never overwrite what the tool did
// not create" for every generated view: an existing file whose first line is not
// the marker is somebody's, and it stays theirs.
func writeMarked(path, marker string, content []byte) error {
	if b, err := os.ReadFile(path); err == nil {
		first, _, _ := strings.Cut(string(b), "\n")
		if first != marker {
			return fmt.Errorf("%s exists and was not generated by libretto wiki — not touching it", path)
		}
	}
	return os.WriteFile(path, content, 0o644)
}

// parseSpec reads one capability spec in a single pass. The intro is the first
// run of prose lines before the first heading after the title; a criterion is a
// bullet block carrying a Proof: line, captured without it.
func parseSpec(r io.Reader, name string) wikiCapability {
	c := wikiCapability{name: name}
	var bullet []string
	bulletProven, introDone, inBullet := false, false, false

	flush := func() {
		if inBullet && bulletProven && len(bullet) > 0 {
			c.criteria = append(c.criteria, strings.Join(bullet, " "))
		}
		bullet, bulletProven, inBullet = nil, false, false
	}

	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)

		switch {
		case strings.HasPrefix(trimmed, "- "):
			flush()
			inBullet = true
			bullet = append(bullet, strings.TrimPrefix(trimmed, "- "))
			continue
		case inBullet && strings.HasPrefix(line, " ") && trimmed != "":
			if strings.HasPrefix(trimmed, "Proof:") {
				bulletProven = true
			} else {
				bullet = append(bullet, trimmed)
			}
			continue
		}
		flush()

		switch {
		case strings.HasPrefix(trimmed, "#"):
			introDone = introDone || strings.HasPrefix(trimmed, "##")
		case strings.HasPrefix(trimmed, "Governs:"):
			if c.governs == "" {
				c.governs = strings.TrimSpace(strings.TrimPrefix(trimmed, "Governs:"))
			}
		case strings.HasPrefix(trimmed, "Targets:"), trimmed == "":
			// structural, never prose
		default:
			if !introDone {
				c.intro = append(c.intro, trimmed)
			}
		}
	}
	flush()
	return c
}

func renderWiki(projectDir string, caps []wikiCapability) []byte {
	var b strings.Builder
	b.WriteString(wikiMarker + "\n\n")
	fmt.Fprintf(&b, "# Specs — %s\n\n", filepath.Base(projectDir))
	b.WriteString("| Capability | Governs | What it promises |\n|---|---|---|\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "| [%s](%s/spec.md) | `%s` | %s |\n",
			c.name, c.name, tableCell(c.governs), tableCell(firstSentence(c.intro)))
	}
	for _, c := range caps {
		fmt.Fprintf(&b, "\n## %s\n\n", c.name)
		if len(c.intro) > 0 {
			b.WriteString(strings.Join(c.intro, " ") + "\n\n")
		}
		if c.governs != "" {
			fmt.Fprintf(&b, "Governs: `%s`\n\n", c.governs)
		}
		for _, crit := range c.criteria {
			fmt.Fprintf(&b, "- %s\n", crit)
		}
		if len(c.criteria) > 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "[full spec](%s/spec.md)\n", c.name)
	}
	return []byte(b.String())
}

func firstSentence(intro []string) string {
	if len(intro) == 0 {
		return ""
	}
	joined := strings.Join(intro, " ")
	if cut := strings.Index(joined, ". "); cut >= 0 {
		return joined[:cut+1]
	}
	return joined
}

// tableCell keeps a pipe in spec prose from tearing the index table apart.
func tableCell(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

// Inline markup arrives from spec prose. Escaping runs first, always: the
// conversions below operate on escaped text, so no raw spec byte ever reaches
// markup position. That order is the whole of the escaping criterion.
var (
	wikiBoldRe = regexp.MustCompile(`\*\*([^*]+)\*\*`)
	wikiCodeRe = regexp.MustCompile("`([^`]+)`")
)

func htmlInline(s string) string {
	s = html.EscapeString(s)
	s = wikiBoldRe.ReplaceAllString(s, "<strong>$1</strong>")
	s = wikiCodeRe.ReplaceAllString(s, "<code>$1</code>")
	return s
}

// wikiGitDate answers "when did this spec last change" from the only clock
// that survives a clone: git history. Any failure — no git, no repository, no
// commits touching the file — is an empty string, and the date is simply
// absent from the page. A var so tests inject dates instead of building repos.
var wikiGitDate = func(projectDir, specPath string) string {
	out, err := exec.Command("git", "-C", projectDir, "log", "-1", "--format=%as", "--", specPath).Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func renderWikiHTML(projectDir string, caps []wikiCapability) []byte {
	name := html.EscapeString(filepath.Base(projectDir))
	total := 0
	maxCrit := 1
	for _, c := range caps {
		total += len(c.criteria)
		if len(c.criteria) > maxCrit {
			maxCrit = len(c.criteria)
		}
	}

	var b strings.Builder
	b.WriteString(wikiHTMLMarker + "\n")
	b.WriteString("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	fmt.Fprintf(&b, "<title>Specs — %s</title>\n", name)
	b.WriteString(`<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Public+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>` + wikiCSS + `</style>
</head>
<body>
<div id="progress"></div>
<main>
<section id="home">
`)
	fmt.Fprintf(&b, "<h1>%s</h1>\n", name)
	fmt.Fprintf(&b, "<p class=\"tag\">%d capabilities · %d anchored criteria · generated by <code>libretto wiki --html</code></p>\n",
		len(caps), total)
	b.WriteString("<input id=\"filter\" type=\"search\" placeholder=\"Filter capabilities and criteria…\" aria-label=\"Filter capabilities and criteria\">\n")
	b.WriteString("<div class=\"cards\">\n")
	for _, c := range caps {
		crit := strings.ToLower(strings.Join(c.criteria, " "))
		fmt.Fprintf(&b, "<a class=\"card\" href=\"#%s\" data-crit=\"%s\">\n", html.EscapeString(c.name), html.EscapeString(crit))
		fmt.Fprintf(&b, "<span class=\"card-name\">%s</span>\n", html.EscapeString(c.name))
		fmt.Fprintf(&b, "<span class=\"card-meta\"><span>%d criteria</span>", len(c.criteria))
		if c.changed != "" {
			fmt.Fprintf(&b, "<span class=\"date\">%s</span>", html.EscapeString(c.changed))
		}
		b.WriteString("</span>\n")
		fmt.Fprintf(&b, "<span class=\"bar\"><i style=\"width:%d%%\"></i></span>\n</a>\n", len(c.criteria)*100/maxCrit)
	}
	b.WriteString("</div>\n</section>\n")
	for _, c := range caps {
		fmt.Fprintf(&b, "<article class=\"cap\" id=\"%s\">\n<a class=\"back\" href=\"#home\">← home</a>\n<h2>%s</h2>\n",
			html.EscapeString(c.name), html.EscapeString(c.name))
		if c.changed != "" {
			fmt.Fprintf(&b, "<p class=\"changed\">last changed <span class=\"date\">%s</span></p>\n", html.EscapeString(c.changed))
		}
		if len(c.intro) > 0 {
			fmt.Fprintf(&b, "<p class=\"intro\">%s</p>\n", htmlInline(strings.Join(c.intro, " ")))
		}
		if c.governs != "" {
			fmt.Fprintf(&b, "<p class=\"governs\"><span class=\"lbl\">Governs</span><code>%s</code></p>\n",
				html.EscapeString(c.governs))
		}
		if len(c.criteria) > 0 {
			b.WriteString("<ul class=\"crit\">\n")
			for _, crit := range c.criteria {
				fmt.Fprintf(&b, "<li>%s</li>\n", htmlInline(crit))
			}
			b.WriteString("</ul>\n")
		} else {
			b.WriteString("<p class=\"none\">No anchored criteria yet — this capability migrates when a delta lands on it.</p>\n")
		}
		b.WriteString("</article>\n")
	}
	b.WriteString("</main>\n<script>" + wikiJS + "</script>\n</body>\n</html>\n")
	return []byte(b.String())
}

// Minimalist and visual at once: the home is the navigation, the cards carry
// the numbers, and colour arrives only through tokens. Dark on the bare :root
// (dark-first per the contract), light complete beside it — every ratio
// measured in the change's plan.
const wikiCSS = `
:root{--ground:#101114;--panel:#17181C;--ink:#E7E5DE;--ink-soft:#A3A49B;
--line:#26272B;--accent:#5CB8A6;--accent-soft:#1D2B28;--code-bg:#1C1E22;
--glass:rgba(231,229,222,.04);--track:rgba(231,229,222,.09)}
@media (prefers-color-scheme: light){:root{--ground:#FAF9F6;--panel:#F1EFE9;--ink:#1F201C;--ink-soft:#5A5B54;
--line:#DDDACF;--accent:#1E6E60;--accent-soft:#E1EDE9;--code-bg:#ECE9E1;
--glass:rgba(31,32,28,.04);--track:rgba(31,32,28,.09)}}
*{box-sizing:border-box}
body{margin:0;color:var(--ink);font:400 16px/1.6 "Public Sans",system-ui,sans-serif;
background:var(--ground)}
#progress{display:none}
main{max-width:56rem;margin:0 auto;padding:3rem clamp(1.25rem,4vw,3rem)}
h1{font-family:"Fraunces",Georgia,serif;font-weight:600;
font-size:clamp(2rem,5vw,2.8rem);margin:0 0 .3rem;text-wrap:balance}
.tag{color:var(--ink-soft);margin:.2rem 0 1.6rem}
#filter{width:100%;max-width:26rem;margin:0 0 1.6rem;padding:.6rem .8rem;
border:1px solid var(--line);border-radius:10px;background:var(--panel);
color:var(--ink);font:inherit;font-size:.92rem}
#filter:focus{outline:2px solid var(--accent);outline-offset:1px}
.cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(15rem,1fr));gap:.8rem}
.card{display:flex;flex-direction:column;gap:.55rem;padding:1rem 1.1rem;
background:var(--panel);border:1px solid var(--line);border-radius:14px;
color:var(--ink);text-decoration:none}
.card:hover,.card:focus-visible{border-color:var(--accent);outline:none}
.card-name{font-family:"Fraunces",Georgia,serif;font-weight:600;font-size:1.12rem}
.card-meta{display:flex;justify-content:space-between;gap:.75rem;
font-size:.78rem;color:var(--ink-soft)}
.date{font:500 .78rem "IBM Plex Mono",monospace;color:var(--ink-soft);
font-variant-numeric:tabular-nums}
.bar{display:block;height:4px;border-radius:2px;background:var(--track);overflow:hidden}
.bar i{display:block;height:100%;border-radius:2px;background:var(--accent)}
article.cap{border-top:1px solid var(--line);margin-top:2.6rem;padding-top:1.6rem}
.back{display:inline-block;margin:0 0 .8rem;color:var(--accent);
text-decoration:none;font-size:.9rem;font-weight:500}
.back:hover,.back:focus-visible{text-decoration:underline;outline:none}
article.cap h2{font-family:"Fraunces",Georgia,serif;font-weight:600;
font-size:1.7rem;margin:0 0 .35rem;scroll-margin-top:1rem}
.changed{margin:.1rem 0 .9rem;font-size:.85rem;color:var(--ink-soft)}
.intro{max-width:44rem;margin:.3rem 0 .9rem}
.governs{display:flex;gap:.7rem;align-items:baseline;flex-wrap:wrap;margin:.4rem 0 1rem}
.governs .lbl{font-size:.72rem;text-transform:uppercase;letter-spacing:.09em;
color:var(--accent);font-weight:600}
code{font:400 .86em "IBM Plex Mono",monospace;background:var(--code-bg);
padding:.1em .35em;border-radius:5px}
.crit{margin:.4rem 0 0;padding-left:1.1rem;display:flex;flex-direction:column;gap:.55rem}
.crit li{max-width:46rem}
.crit li::marker{color:var(--accent)}
.none{color:var(--ink-soft);font-style:italic;font-size:.92rem;max-width:44rem}
.hidden{display:none}
body.paged #home{display:none}
body.paged article.cap{display:none}
body.paged article.cap.open{display:block;border-top:none;margin-top:0}
@media (prefers-reduced-motion: no-preference){
html{scroll-behavior:smooth}
@keyframes fill-x{from{transform:scaleX(0)}to{transform:scaleX(1)}}
#progress{display:block;position:fixed;top:0;left:0;right:0;height:3px;z-index:2;
background:var(--accent);transform-origin:0 50%;animation:fill-x linear;animation-timeline:scroll()}
@keyframes rise{from{opacity:.15;transform:translateY(14px)}to{opacity:1;transform:none}}
.cap{animation:rise linear both;animation-timeline:view();animation-range:entry 0% entry 40%}
}/*end-motion*/
`

const wikiJS = `
// Router: enhancement only. Without this block the whole wiki renders stacked
// and every anchor still lands; with it, one page shows at a time.
function route(){
  const id=location.hash.slice(1);
  const target=id&&document.getElementById(id);
  const isPage=!!(target&&target.classList.contains('cap'));
  document.body.classList.toggle('paged',isPage);
  document.querySelectorAll('article.cap.open').forEach(a=>a.classList.remove('open'));
  if(isPage) target.classList.add('open');
}
addEventListener('hashchange',route);
route();
// Home search: cards filter on their name and the data-crit text they carry.
const input=document.getElementById('filter');
input.addEventListener('input',()=>{
  const q=input.value.trim().toLowerCase();
  document.querySelectorAll('.card').forEach(card=>{
    const hit=!q||card.textContent.toLowerCase().includes(q)||(card.dataset.crit||'').includes(q);
    card.classList.toggle('hidden',!hit);
  });
});
`
